services:
  redis:
    image: redis:7.2    
    container_name: redis-server
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"  
    depends_on:
      - redis
